In [19]:
import os
import pandas as pd
import numpy as np

In [11]:

def concat_csv_files(folder_path):
  # Get all CSV files in the folder
  csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

  # Create an empty DataFrame to store the concatenated data
  df = pd.DataFrame()

  # Iterate over all CSV files and read them into the DataFrame
  for file in csv_files:
    file_path = os.path.join(folder_path, file)
    temp_df = pd.read_csv(file_path)
    df = pd.concat([df, temp_df], ignore_index=True)

  return df

# Example usage
folder_path = 'ps'  # Replace with the actual path to your folder
df = concat_csv_files(folder_path)

# Print the concatenated DataFrame
print(df)

    tipo  hidden_layer_sizes  learnRate  dropout  batchSize  fold  \
0    SEM                 784     0.0001      0.4         16     1
1    COM                 512     0.0100      0.3         16     2
2    COM                 256     0.0010      0.5         32     1
3    COM                 512     0.0100      0.5         16     0
4    COM                 784     0.0100      0.5         32     2
..   ...                 ...        ...      ...        ...   ...
319  SEM                 784     0.0001      0.4         16     0
320  SEM                 256     0.0010      0.4         32     1
321  SEM                 256     0.0100      0.3         32     1
322  SEM                 784     0.0010      0.4         16     2
323  SEM                 256     0.0100      0.5         16     2

              MAE
0        0.889167
1    10709.023078
2        0.045432
3       29.883180
4    85993.957314
..            ...
319      1.459780
320      0.092543
321      0.098416
322      0.844407
323   2636.871817

[324 rows x 7 columns]

In [12]:
df[df['tipo'] == 'COM']

,tipo,hidden_layer_sizes,learnRate,dropout,batchSize,fold,MAE
1,COM,512,0.0100,0.3,16,2,10709.023078
2,COM,256,0.0010,0.5,32,1,0.045432
3,COM,512,0.0100,0.5,16,0,29.883180
4,COM,784,0.0100,0.5,32,2,85993.957314
5,COM,256,0.0010,0.3,16,0,0.070629
...,...,...,...,...,...,...,...
307,COM,256,0.0100,0.5,32,1,29.219212
309,COM,256,0.0010,0.5,16,2,0.416933
314,COM,512,0.0001,0.3,16,0,0.693251
315,COM,512,0.0010,0.4,16,0,0.054305
318,COM,512,0.0001,0.4,16,1,0.117588

In [13]:
df[df['tipo'] == 'SEM']

    tipo  hidden_layer_sizes  learnRate  dropout  batchSize  fold          MAE
0    SEM                 784     0.0001      0.4         16     1     0.889167
7    SEM                 512     0.0100      0.3         32     1  2047.719479
11   SEM                 512     0.0001      0.5         16     0     1.259415
13   SEM                 512     0.0010      0.3         32     1     0.099064
17   SEM                 256     0.0100      0.4         32     2     0.072950
..   ...                 ...        ...      ...        ...   ...          ...
319  SEM                 784     0.0001      0.4         16     0     1.459780
320  SEM                 256     0.0010      0.4         32     1     0.092543
321  SEM                 256     0.0100      0.3         32     1     0.098416
322  SEM                 784     0.0010      0.4         16     2     0.844407
323  SEM                 256     0.0100      0.5         16     2  2636.871817

[162 rows x 7 columns]

In [16]:
new_vals = {}
original_vals = df.values
for tipo, fls, lr, do, bs, j, mae in original_vals:
    if (tipo, fls, lr, do, bs) in new_vals.keys():
        new_vals[(tipo, fls, lr, do, bs)] += mae
    else:
        new_vals[(tipo, fls, lr, do, bs)] = mae
    
for k in new_vals:
    new_vals[k] = new_vals[k]/3
new_vals

{('SEM', 784, 0.0001, 0.4, 16): 1.0222780037596144,
 ('COM', 512, 0.01, 0.3, 16): 210966.41172627013,
 ('COM', 256, 0.001, 0.5, 32): 0.609216362632281,
 ('COM', 512, 0.01, 0.5, 16): 2504.3029993948744,
 ('COM', 784, 0.01, 0.5, 32): 28787.19584859224,
 ('COM', 256, 0.001, 0.3, 16): 0.22856568352387155,
 ('SEM', 512, 0.01, 0.3, 32): 682.9889894135096,
 ('COM', 512, 0.001, 0.4, 32): 0.37181344743842537,
 ('COM', 256, 0.01, 0.4, 16): 1076.3951338201098,
 ('COM', 256, 0.001, 0.5, 16): 0.4138744961326533,
 ('SEM', 512, 0.0001, 0.5, 16): 0.7432346547534839,
 ('COM', 256, 0.0001, 0.5, 16): 0.46583406574320896,
 ('SEM', 512, 0.001, 0.3, 32): 0.10529273375553473,
 ('COM', 784, 0.0001, 0.4, 16): 0.2958435027053297,
 ('COM', 256, 0.0001, 0.4, 16): 0.43512653277888497,
 ('COM', 784, 0.001, 0.4, 32): 0.1397303328575227,
 ('SEM', 256, 0.01, 0.4, 32): 0.12684549753502386,
 ('SEM', 784, 0.01, 0.5, 16): 724.6199394707778,
 ('COM', 256, 0.01, 0.5, 16): 3225.317859450439,
 ('SEM', 784, 0.001, 0.3, 32): 0.18699664902186866,
 ('SEM', 784, 0.001, 0.5, 16): 0.2133641592588699,
 ('COM', 784, 0.001, 0.3, 16): 1.1683881338730477,
 ('SEM', 512, 0.001, 0.5, 16): 0.3630901373838816,
 ('COM', 784, 0.01, 0.3, 32): 941.9617293614073,
 ('SEM', 256, 0.0001, 0.5, 16): 0.9921788448877006,
 ('COM', 512, 0.0001, 0.3, 32): 0.4041132351397689,
 ('SEM', 512, 0.001, 0.4, 32): 0.21059917998016695,
 ('COM', 256, 0.0001, 0.5, 32): 0.5074541060400867,
 ('SEM', 512, 0.01, 0.3, 16): 3390.684777505808,
 ('COM', 784, 0.01, 0.4, 32): 4441.624023969944,
 ('SEM', 256, 0.001, 0.5, 32): 0.1721471431924165,
 ('COM', 784, 0.0001, 0.4, 32): 0.3648083950286462,
 ('COM', 512, 0.01, 0.3, 32): 622.0311286499082,
 ('COM', 784, 0.001, 0.4, 16): 1.5711260748587943,
 ('COM', 256, 0.001, 0.4, 16): 0.4296629070573221,
 ('COM', 512, 0.0001, 0.5, 16): 0.36574012443853116,
 ('SEM', 256, 0.0001, 0.5, 32): 0.633100583544774,
 ('COM', 256, 0.01, 0.3, 32): 352.1538212669561,
 ('SEM', 512, 0.001, 0.4, 16): 0.37521420756609736,
 ('SEM', 512, 0.01, 0.5, 32): 2.579923650621146,
 ('COM', 256, 0.0001, 0.3, 16): 0.41724354669485947,
 ('COM', 512, 0.001, 0.3, 32): 0.11447298902499094,
 ('SEM', 256, 0.01, 0.4, 16): 333.88200067121346,
 ('SEM', 256, 0.0001, 0.3, 32): 0.28144517918590317,
 ('COM', 256, 0.01, 0.4, 32): 343.3571934067284,
 ('COM', 512, 0.001, 0.3, 16): 0.05348593366813644,
 ('COM', 512, 0.0001, 0.4, 32): 0.4216252392199069,
 ('SEM', 784, 0.01, 0.5, 32): 139.40336872635248,
 ('COM', 784, 0.0001, 0.3, 16): 0.5072058860255421,
 ('SEM', 512, 0.0001, 0.3, 32): 0.48353619960236216,
 ('SEM', 256, 0.01, 0.3, 16): 529.2311729449362,
 ('COM', 784, 0.001, 0.3, 32): 0.12777620891238725,
 ('SEM', 784, 0.0001, 0.5, 16): 0.75750131978022,
 ('COM', 512, 0.001, 0.4, 16): 0.13721920401230422,
 ('SEM', 256, 0.0001, 0.4, 16): 0.6810832235097934,
 ('COM', 256, 0.01, 0.5, 32): 13.031141409125189,
 ('COM', 512, 0.0001, 0.5, 32): 0.3499859679977046,
 ('SEM', 256, 0.001, 0.3, 16): 0.411904300814203,
 ('SEM', 784, 0.001, 0.5, 32): 0.16133723488070834,
 ('SEM', 784, 0.001, 0.3, 16): 0.34086471716770633,
 ('SEM', 784, 0.0001, 0.5, 32): 0.4237730881720305,
 ('SEM', 512, 0.01, 0.4, 32): 0.5488876545402818,
 ('SEM', 256, 0.001, 0.3, 32): 0.17723584722166685,
 ('SEM', 256, 0.0001, 0.4, 32): 0.32129074206116753,
 ('SEM', 512, 0.0001, 0.3, 16): 0.9213878148149489,
 ('SEM', 256, 0.01, 0.3, 32): 0.8129091633453469,
 ('SEM', 784, 0.0001, 0.3, 32): 1.0705112309382299,
 ('COM', 784, 0.0001, 0.3, 32): 0.39695630959751477,
 ('COM', 512, 0.0001, 0.4, 16): 0.4418718557992953,
 ('SEM', 256, 0.01, 0.5, 16): 879.7572836318299,
 ('SEM', 256, 0.01, 0.5, 32): 0.48839036800878666,
 ('COM', 784, 0.0001, 0.5, 16): 0.34750265463598945,
 ('COM', 512, 0.01, 0.4, 16): 2829.8984288663232,
 ('COM', 256, 0.0001, 0.4, 32): 0.486369933237821,
 ('COM', 256, 0.001, 0.3, 32): 0.16683451446094577,
 ('SEM', 784, 0.001, 0.4, 32): 0.3094353539599814,
 ('SEM', 256, 0.001, 0.5, 16): 0.5734120313286798,
 ('SEM', 784, 0.0001, 0.3, 16): 0.8739212136399298,
 ('COM', 784, 0.01, 0.5, 16): 184225.23699382716,
 ('COM', 784, 0.01, 0.3, 16): 6298.33181914493,
 ('COM', 784, 0.001, 0.5, 32): 0.2513531866094633,
 ('COM', 256, 0.01, 0.3, 16): 5914.2112302493915,
 ('COM', 256, 0.0001, 0.3, 32): 0.5220350122082077,
 ('SEM', 512, 0.0001, 0.5, 32): 0.48297862594386354,
 ('SEM', 784, 0.01, 0.3, 32): 669.8508660494077,
 ('SEM', 512, 0.001, 0.3, 16): 0.33547324235131537,
 ('COM', 512, 0.01, 0.5, 32): 748.0415087780915,
 ('COM', 512, 0.01, 0.4, 32): 798.9468349231338,
 ('SEM', 512, 0.01, 0.5, 16): 172.83570556417024,
 ('COM', 512, 0.001, 0.5, 32): 0.1952437952453747,
 ('SEM', 512, 0.01, 0.4, 16): 3040.976229161069,
 ('SEM', 784, 0.01, 0.4, 16): 2823.2655249966574,
 ('SEM', 512, 0.0001, 0.4, 16): 0.8591876867082853,
 ('COM', 784, 0.001, 0.5, 16): 0.7857522745254907,
 ('COM', 784, 0.01, 0.4, 16): 30595.095543680432,
 ('COM', 256, 0.001, 0.4, 32): 0.161828993488064,
 ('SEM', 512, 0.0001, 0.4, 32): 0.5126015978276186,
 ('SEM', 256, 0.0001, 0.3, 16): 0.9789344102057527,
 ('COM', 512, 0.0001, 0.3, 16): 0.45697006704305626,
 ('COM', 512, 0.001, 0.5, 16): 0.720077600199937,
 ('COM', 784, 0.0001, 0.5, 32): 0.24797296754153456,
 ('SEM', 784, 0.0001, 0.4, 32): 0.46749955840212554,
 ('SEM', 784, 0.01, 0.4, 32): 163.9967587329846,
 ('SEM', 784, 0.001, 0.4, 16): 0.5109247234659196,
 ('SEM', 784, 0.01, 0.3, 16): 14231.477977081951,
 ('SEM', 256, 0.001, 0.4, 32): 0.11537636742320596,
 ('SEM', 512, 0.001, 0.5, 32): 0.1767953572928498,
 ('SEM', 256, 0.001, 0.4, 16): 0.1772479778201146}

In [29]:
novo_df = pd.DataFrame(new_vals.values(), index=new_vals.keys())
novo_df = novo_df.sort_values(by=0, ascending=True)
novo_df

                                  0
COM 512 0.001 0.3 16       0.053486
SEM 512 0.001 0.3 32       0.105293
COM 512 0.001 0.3 32       0.114473
SEM 256 0.001 0.4 32       0.115376
        0.010 0.4 32       0.126845
...                             ...
    784 0.010 0.3 16   14231.477977
COM 784 0.010 0.5 32   28787.195849
              0.4 16   30595.095544
              0.5 16  184225.236994
    512 0.010 0.3 16  210966.411726

[108 rows x 1 columns]